fix(example): allow demo to run with --all-features
Crossterm and termion features are mutually exclusive in the example
code, so pick crossterm over termion by using cfg_if!() when running:
`cargo run --all-features`

Fixes:
error[E0252]: the name `run` is defined multiple times
  --> examples/demo/main.rs:11:5